### ISSUE TITLE
Bookmark/directly access a page or scroll position

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#100]
## User Storey

As a user, I want to be able to bookmark the page where I am currently on on the grid. I should be able to return the the page directly via the bookmarked url.

This should work for both paged and scrolled paging types.

**Comment by jodysalt** [comment]
I haven't found a way to save/restore the scroll position. However, I've managed to get it to save/restore the page number (in page mode), the filters and the sorting.

So I haven't satisfied all the requirements but very nearly (hence I havn't moved this ticket to done yet).

**Comment by wayne-chung** [comment]
Noticed that the filter string enter for investigation sticks around and get applied to the next entity (dataset) in the hierachy. This often filter out all the results!

**Comment by wayne-chung** [comment]
Odd. It doesn't seem to happeing now.

**Comment by jodysalt** [comment]
This works for paged paging types. However, there doesn't seem to be a satisfactory way to achieve scrolled based paging with ui grid. I would like to suggest that if bookmarkable paging is  important to a particular organisation, then you probably wouldn't want to use scroll based paging anyway because in order to access distant pages in scrolling mode you first have to load in all the previous pages.  I will close this now as and re-open as a separate issue if scroll based paging is really a requirement.
