### ISSUE TITLE
Human readable bytes format 1000 vs 1024

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#137]
Human readable bytes format are currently calculate using 1000 rather than 1024.

**Comment by RKrahl** [comment]
I guess, we should adhere to international standards, which codify that one kB = 1000 B, while one KiB = 1024 B, see the [Binary prefix Wikipedia page](https://en.wikipedia.org/wiki/Binary_prefix).

**Comment by tomgriffinstfc** [comment]
We need to match the behaviour users will expect. If a user downloads a file set and runs "df -h" they will see a value and we need to show the same value  or a user will be concerned something is wrong.

**Comment by RKrahl** [comment]
Am Montag, 30. November 2015, 07:30:17 schrieb Tom Griffin:
> We need to match the behaviour users will expect. If a user
> downloads a file set and runs "df -h" they will see a value and we
> need to show the same value or a user will be concerned something is
> wrong.

That would be powers of 1024.  I'm happy with that.  I only suggest
that we use the correct binary prefixes in this case, e.g. KiB, MiB,
and GiB instead of kB, MB, and GB.  I guess, users who don't know
these prefixes won't even notice the difference.  For users who do
know them, it will remove the ambiguity from the figures.

**Comment by jodysalt** [comment]
Add feature to language.json
