### ISSUE TITLE
Frontend/command line tool for admin tasks

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#138]
It would be nice to have a frontend and/or command line tool to perform admin tasks such as start/stop polling, displaying download requests rather than just the admin RESTAPI.

**Comment by kevinphippsstfc** [comment]
It would be painful to have to go live without this!

**Comment by jodysalt** [comment]
I've had more thoughts on this.

I propose we scrap the polling rest API. And instead expose an API that allows us to change the download state between 'RESTORING', 'PAUSED', 'DELETED', 'COMPLETE'.

So basically if the download state is 'RESTORING' then you should be able to guarentee that the Topcat server will be polling the Ids server, otherwise (if it is in any other state) you should be able to guarentee it won't be polling.

So even after a restart the Topcat server should automically start the polling for downloads with the 'RESTORING' state. If it doesn't do this it is a bug (not a feature).

This would simplify the API by removing details which Topcat (rest application) clients shouldn't need to be concerned with.

Also this proposal with simplify the admin backend, as you will remove extra features required to start and stop the polling for each download, despite potentualy being in a 'RESTORING' state which is just confusing.

What are your thoughts on this?

**Comment by jodysalt** [comment]
Another state which would be usefull is 'FAILED'. e.g. if the prepared is invalid on the IDS side, or if the download gets paused and the problem can't be fixed.

**Comment by jodysalt** [comment]
This 'FAILED' state feature (along with the scrapping of the polling rest api, and the other states) would tie in quite nicley with #151.
