### ISSUE TITLE
topcat.json

### ISSUE THREAD

**Issue by fisherab** [icatproject/topcat#229]
- For a facility only the idsUrl need be specified and not the icatUrl (as the icatUrl can be found from an ids call)
- In the json, facilities should contain facility and not facilityName
- facilityDatabaseName is not a good name. I think this should be just facilityName
- title should be taken from icat
- authentication types can be derived from icat and need not be specified here. I presume that anon is hard coded to behave differently - Ugh

**Comment by fisherab** [comment]
I decided to label this as a bug as it best to get the json field names right now

**Comment by fisherab** [comment]
If you agree to have facilities as an array of facility then "facilityDatabaseName" can simply be "name"

**Comment by jodysalt** [comment]
I partially agree - since it's already in a "facilities" namespace it already has context. However, my logic was to highlight that it has to be the facility name exactly as it appears on the Database. Someone might come along and think they can have "DLS", "Diamond Light" or "DIAMOND" (which they can't). The other alternative I considered, was to call it 'databaseName' - which would be even more confusing!

**Comment by jodysalt** [comment]
maybe "nameAsItAppearsOnDatabase" ? Little verbose but hammers home point.

**Comment by jodysalt** [comment]
The title can't be pulled from Icat as it is required before login, and in order get the title you have to be logged in (i.e. have a sessionId).

**Comment by jodysalt** [comment]
Need feed backback on #233
