### ISSUE TITLE
ordering by a combined column doesn't work

### ISSUE THREAD

**Issue by jodysalt** [icatproject/topcat#255]
order by concat(var1, '-', var2) is not valid jpql

**Comment by RKrahl** [comment]
You could `order by var1, var2` instead, this should be equivalent.

Since this was originally needed in #126, I would also be happy if one would need to put something like the following in topcat.json:
```javascript
{
    "field": "investigationVisit",
    "jpqlFilter": "CONCAT(investigation.name, '-', investigation.visitId)",
    "jpqlSort": "investigation.name, investigation.visitId",
    "cellTemplate": "<div class='ui-grid-cell-contents'>{{row.entity.name}}-{{row.entity.visitId}}</div>"
}
````
E.g. it's ok if TopCAT does not automatically extracts the list of variables for sorting out of jpqlExpression.

**Comment by jodysalt** [comment]
I think your suggestion is better. To the end user I think it would be the expected behaviour, as concat will sort things alpha numerically. Maybe if steve decides to allow calculated fields I could add further jpqlSelect (where you could specify for example concat(var1, '-', var2)  as foo - and then sort by foo) option - which would make things very flexible.
