### ISSUE TITLE
Make displaying dataset details and parameters more intuitive

### ISSUE THREAD

**Issue by andygotz** [icatproject/topcat#286]
The current solution to display the details and parameters tab for a dataset or file is not at all intuitive. One has to click on the empty space in the cell of the dataset or file. It would be more intuitive if there was a column which could allow selecting which datasets or files should have their details and parameters shown. One should be possible to have multiple datasets and files selected. The selected ones should be highlighted to make it clear they are selected.

**Comment by RKrahl** [comment]
We already discussed this on the mailing list in Oct 2015.  My suggestion then was:

> Maybe a small "i" icon displayed as a bullet in front of each row would do.  Something similar to the 
> way Leo (an online dictionary, see http://leo.org/) is presenting its results.

The only thing that would need to be done is adding that static column with the icon in each row.  Since it is passive text, clicking on it would already have the expected result.

For your suggestion of being able to select multiple dataset at once, how do you suggest this could be displayed in the tabs?
