### ISSUE TITLE
Single button download for datasets

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#304]
The ISIS topcat has a (blue) download button to allow easy download of a datafile.

I'd like the same for dataset: an obvious download button to allow one-click download of a dataset.

This would need to be configurable as it probably only makes sense for 1-level storage

**Comment by jodysalt** [comment]
There is a problem with  this.

At the moment if an investigation only has one dataset, it will skip past it and go straight to the datafile level.

There are three possible solutions:

* also allow download buttons at the investigation level.
* have a "download all" button at the datafile level
* enable the grid's select all tick box - this also has the advantage of being able to apply filters.

Let me know your thoughts.

**Comment by jodysalt** [comment]
There is also a 4th solution:

* Remove the skipping feature, and just accept that even if there is only one dataset the user will have to browse past. Having this download feature could make this justifiable, and also perhaps the skipping feature might be creating more confusion than good - it would be sort of like windows explorer skipping past directories with no siblings.

**Comment by RKrahl** [comment]
Just one remark: I was not aware of this skipping feature until now.  I just tried it with the current snapshot topcat-2.2.1-20170103.153556-2 and here it does not seem to skip through, but rather also displays the dataset level.

Maybe this is related to my particular configuration.  But anyway, there would be a major disadvantage of this skipping feature: we here at HZB define most meta data on the dataset level, using DatasetParameter rather then DatafileParameter, because we consider these as parameter of the measurement (which is represented by the dataset) rather then as parameter of the resulting file.  If you skip straight to the datafile level, the user has no way to get these parameter displayed in topcat.  But these parameter may be important to the user.

So this may be an argument in favor of the 4th solution.

**Comment by tomgriffinstfc** [comment]
I don't think the ISIS implementation/live version has the skipping feature enabled.

You proposed four options.

As far as I can see, these will make it even easier for the user and offer more choice

- [ ] Remove the skipping feature
Yes, as it does not seem to be there

- [ ] also allow download buttons at the investigation level.
- [ ] have a "download all" button at the datafile level
- [ ] enable the grid's select all tick box - this also has the advantage of being able to apply filters.

Adding all three would give the best user experience.
