### ISSUE TITLE
Possible problem with searching

### ISSUE THREAD

**Issue by fisherab** [icatproject/topcat#319]
This was reported via [RT](
<URL: https://helpdesk.gridpp.rl.ac.uk:443/Ticket/Display.html?id=182380 >) and so once it is closed will also need attention there.
![icat_search](https://cloud.githubusercontent.com/assets/2564342/24711599/57ef0fde-1a18-11e7-8fa1-61c2670834da.png)
![icat_browse](https://cloud.githubusercontent.com/assets/2564342/24711611/5e24f396-1a18-11e7-8136-c3b110a16826.png)

I have marked it as high priority because it has been open for some time.

**Comment by jodysalt** [comment]
Works on my machine :) :

[cid:F4A85BA3-338D-42D6-877D-5AA3DF60ECD4@esc.rl.ac.uk]



Maybe it is a permissions problem?

Jody






On 5 Apr 2017, at 15:57, Steve Fisher <notifications@github.com<mailto:notifications@github.com>> wrote:


This was reported via [RT](
<URL: https://helpdesk.gridpp.rl.ac.uk:443/Ticket/Display.html?id=182380<https://helpdesk.gridpp.rl.ac.uk/Ticket/Display.html?id=182380> >) and so once it is closed will also need attention there.
[icat_search]<https://cloud.githubusercontent.com/assets/2564342/24711599/57ef0fde-1a18-11e7-8fa1-61c2670834da.png>
[icat_browse]<https://cloud.githubusercontent.com/assets/2564342/24711611/5e24f396-1a18-11e7-8136-c3b110a16826.png>

I have marked it as high priority because it has been open for some time.

**Comment by jodysalt** [comment]
It now works!

**Comment by dfq16044** [comment]
This ticket is still an issue.
I tried the search and it does not work. Is it possible to reopen this ticket?

**Comment by jodysalt** [comment]
It is working fine for me. Can you describe what you are doing?

**Comment by dfq16044** [comment]
It is not displaying the datafile/dataset for the beamline i18 for 54192 scan.
However, when we have a rall it is displaying the corresponding datafile/dataset for other beamline like i20

**Comment by jodysalt** [comment]
Hi Sylvie,

You are going to have to come and show me, as I can't seem to replicate it.

Jody

**Comment by jodysalt** [comment]
This is an issue with Lucene
