### ISSUE TITLE
Allows users to grant permissions on their investigations

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#329]
PIs should be able to grant additional people permission to access the data they own.
This follows on from ICAT issues
https://github.com/icatproject/icat.server/issues/78
https://github.com/icatproject/icat.server/issues/97 
and possibly https://github.com/icatproject/icat.server/issues/116

PIs should also be able to make an investigation public/read all

**Comment by jodysalt** [comment]
Hi Tom,

Can you clarify? Is it just at the investigation level you want to allow users grant permissions (which is very straight forward - just an InvestigationUser who's role is 'reader'). Or do you envisage PI's cherry picking datasets/datafiles etc (which will be very messy - probabley the use of a DataCollection with a 'user' ParameterType).

Jody

**Comment by tomgriffinstfc** [comment]
Just investigation would be sufficient for now - that is the request from end users.

Thanks,
Tom

**Comment by RKrahl** [comment]
Hi all,

I'm afraid, it's not that straight forward at all.  It depends on the way the rules and permissions are set up in ICAT and there are very different approaches for that.  For HZB for instance, you must not add an InvestigationUser (and certainly won't have permission to do so in the first place), but rather need to add the user to a particular group that is related to the Investigation by an InvestigationGroup.

Also the question who should have the privilege to grant permissions on an investigation is not as obvious as it may seem.  It is not for all sites that you could simply take an InvestigationUser having a particular role as indication.  For HZB for instance, we do not even have a PI, at least not when it comes to manage permissions.  In an early (now outdated) concept, it would have been again members of another particular group to have this grant privilege.  In the meanwhile, the procedure is even more complicated then that.

At HZB, we may be not concerned with this feature, because at least for the moment, we plan to manage grant of permissions outside of TopCAT.  But I wanted to add this remark nevertheless as a warning that I believe it will be very difficult to implement this in a way such it would work for more then only a few sites.  Maybe a site specific plugin would be needed.
