### ISSUE TITLE
Download via cart returns internal IDS url to the user

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#370]
I found a bug in the `topcat-2.4.0-20180416.111123-1` snapshot. Note that the bug is not in any released version, as the distinction between internal and external url has only been added recently and not yet been released.

I'm in the same situation as described in #357: I have TopCat together with all other ICAT components in a Payara server, lets say listening on `http://icat.internal.example.org:8080/`. This host is in an internal network and cannot be reached from outside by the user. All user requests are forwarded to Payara by an Apache reverse proxy listening on `https://icat.example.org/`. The Payara server on the other hand cannot reach the external host name. So all communication between individual ICAT components must use the internal url.

Thanks to the solution implemented in #357 this works very well most of the time, having the internal url configured in `topcat.properties` and the external url in `topcat.json`. So I have:
```
facility.list = ESNF

facility.ESNF.icatUrl = http://icat.internal.example.org:8080
facility.ESNF.idsUrl = http://icat.internal.example.org:8080

facility.ESNF.downloadType.http = http://icat.internal.example.org:8080
```
in `topcat.properties` and
```
{    
    "site": {
        "topcatUrl": "https://icat.example.org",
	[...]
    },
    "facilities": [
        {
            "name": "ESNF",
            "title": "ESNF",
            "idsUrl": "https://icat.example.org",
            "icatUrl": "https://icat.example.org",
	    [...]
            "downloadTransportTypes": [
                {
                    "type" : "https",
                    "idsUrl": "https://icat.example.org"
                }
            ],
	    [...]
    ],
    [...]
}
```
in `topcat.json`.

But it fails for downloading data using the cart: I add stuff to the cart, hit the `Download Cart` button. Eventually the download becomes available in the `Downloads` window. When I hit the `Download` button here, it returns the url `http://icat.internal.example.org:8080/ids/getData?preparedId=<some-id>&outname=<some-name>`, which obviously cannot work for the user. If I manually replace the host part in the url to `https://icat.example.org/ids/getData?preparedId=<some-id>&outname=<some-name>`, the download succeeds.

Direct download using the `Download` button next to a single file works as well.

**Comment by brianritchie1312** [comment]
I can see what's happening. When the OK button is clicked in the Download dialog (after clicking Download Cart), a POST request is sent to the Java client to "submit" the cart. This creates a persistent object for the download, which stores a "transportUrl" whose value is based on the downloadType defined in topcat.properties. When the Javascript retrieves the download from the Java side, it uses the transportUrl to construct a getData request. So if the transportUrl is set to the "internal" IDS URL, it will not work. This suggests that changing the value in topcat.properties to use the "external" URL rather than the "internal" one should work; in this case:

`facility.ESNF.downloadType.http = http://icat.example.org`

I believe that the downloadType values are only used for this purpose and are not used anywhere else in the Java code. If this is correct, then all that needs to be done is to change the documentation!

The Download button on individual files sends a getData request to the facility's IDS from Javascript, using the URL defined in topcat.json, and doesn't use the Java side at all.

**Comment by RKrahl** [comment]
But if that is the case, that the url in downloadType is actually only used on the client side, then it it shouldn't be configured in `topcat.properties` in the first place. The idea was that the urls configured in `topcat.properties` are for the internal communication between the ICAT components and the urls in `topcat.json` for the connections from the user. I'd suggest to keep that consistent.

You might for instance store only the local part `/ids/getData?preparedId=<some-id>&outname=<some-name>` in the persistent object. When the Javascript constructs the getData request, it would prepend the url configured in `topcat.json` for the download type of that site to whatever local part it gets from the server for the download.

**Comment by brianritchie1312** [comment]
I agree. When I replaced the original full URL with the facility name I had assumed that it was being used somewhere on the Java side, and didn't appreciate that it was only being stored to be returned to the Javascript on request. (Of course, this also means that the full URL can still be seen in the response.)
I will change the code to work as you suggest.

**Comment by RKrahl** [comment]
It's even more complicated: at least in my configuration, the user needs to access the ids.server with https, while topcat must use http. E.g. there is even no common transport type unless you take these two as synonyms.
--
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

________________________________

Helmholtz-Zentrum Berlin für Materialien und Energie GmbH

Mitglied der Hermann von Helmholtz-Gemeinschaft Deutscher Forschungszentren e.V.

Aufsichtsrat: Vorsitzender Dr. Karl Eugen Huthmacher, stv. Vorsitzende Dr. Jutta Koch-Unterseher
Geschäftsführung: Prof. Dr. Bernd Rech (kommissarisch), Thomas Frederking

Sitz Berlin, AG Charlottenburg, 89 HRB 5583

Postadresse:
Hahn-Meitner-Platz 1
D-14109 Berlin

https://www.helmholtz-berlin.de

**Comment by brianritchie1312** [comment]
I think that the solution would be to define:

`facility.ESNF.downloadType.https = http://icat.internal.example.org:8080`

in topcat.properties; that is, to think of this as defining what IDS url the Java side should use when a submitCart is received from Topcat for download type 'https'.

This would only work once the Javascript side no longer uses the transportUrl that it gets from Java.

I think that the transportUrl should no longer be stored in the Download object, but each side should use whatever URL is in its configuration for that download type (or transport type, since both terms are used). 

The transportUrl is used in two places in Topcat; the "OK button" in the Download Cart dialog will be easy to replace; I'm less certain about the Download button in the Download cart itself.
