### ISSUE TITLE
File upload fails with error message

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#371]
File upload does not seem to work with the new snapshot 2.4.0-20180501.143404-2.  The symptom:

1. In the investigation tab, hit the `Upload` button.
2. The upload dialog opens.  Choose a `Dataset name` and drop some files in the `Files` field.
3. Hit `Upload`.
4. An error message `One to many related objects should not have the id value set: {}` shows, the upload dialog remains open.  The only way out is the `Cancel` button.

A look into the icat.log seem to hint at the cause:
```
2018-05-02 10:59:15,938 INFO [http-thread-pool::jk-connector(1)] EntityBeanManager - write called with [{"Dataset":{"investigation":{"id":36},"type":{},"name":"testul"}}]
2018-05-02 10:59:15,941 INFO [http-thread-pool::jk-connector(1)] GateKeeper - Consider {"id":36}
2018-05-02 10:59:15,942 INFO [http-thread-pool::jk-connector(1)] IcatExceptionMapper - Processing BAD_PARAMETER: One to many related objects should not have the id value set: {}
```
TopCAT tries to create the dataset with an empty type, which cannot work.  Indeed, there is a suspicious commit fcd4684 ("disabled upload feature to simplify first time install").  But this does not disable uploads – the upload button is still there – and even if I add `idsUploadDatafileFormat`, `idsUploadDatasetType`, and `idsUploadMaxTotalFileSize` back to `topcat,json` the described behavior remains the same.

**Comment by RKrahl** [comment]
Note that in TopCAT 2.3.6 as well as in the previous snapshot (after adding `idsUploadDatafileFormat`, `idsUploadDatasetType`, and `idsUploadMaxTotalFileSize` back to `topcat,json`) I got past this error, but I encounter another issue with file upload. Since this seem to be unrelated, I'll report that separately.

**Comment by brianritchie1312** [comment]
I hadn't looked at the Upload code before (apart from making it pass the facilityName rather than the idsUrl to Java). Looking now, I think I see what the immediate problem is here: the commit referenced above removes the idsUploadBlah properties from topcat.json.example; but the appearance of the Upload button is controlled by another property, `browse/dataset/gridOptions/enableUpload` (for each facility). This is set to `"true"` in topcat.json.example (and in the other topcat.json versions I've looked at). So the button appears, but there is no idsUploadDatasetType etc. to go with it. Topcat doesn't appear to check this; it probably should. 

If idsUploadDatasetType or idsUploadDatafileFormat are set, Topcat will attempt to get the corresponding Ids from ICAT, but will only log a message to the browser console if the lookup fails.

So an immediate workaround is to set `enableUpload` to false everywhere. I'm not certain whether Upload really should be disabled by default; if so, this change should be made to topcat.json.example.

I notice too that the URL to which the upload request is sent uses the topcatUrl but replaces `https://` with `wss://` and `http://` (or anything else) with `ws://`. Might this have consequences when working with a proxy/firewall?

**Comment by RKrahl** [comment]
I have to amend my report: I thought to have observed the described behavior in the last snapshot 2.4.0-20180501.143404-2 **even after** adding `idsUploadDatafileFormat`, `idsUploadDatasetType`, and `idsUploadMaxTotalFileSize` back to `topcat.json`. Now I double checked and found that this is not the case.

So in fact, the problem was only these missing values and adding them back to `topcat.json.example` will solve this issue. Concerning the default for `enableUpload`, I'm somewhat indifferent.  Maybe it would indeed be good to set it to false so that upload must be enabled consciously by the site admin.

Concerning `ws://` and `wss://`, this is the [WebSocket](https://en.wikipedia.org/wiki/WebSocket) protocol.  And yes, that may be the cause for #372.

**Comment by brianritchie1312** [comment]
I'm not certain what motivated the removal of `idsUploadDatafileFormat `etc. I think that Topcat should check that if `enableUpload `is set then these properties should be set too, and warn if they are not (and hide the Upload button). However, at present Topcat can only "warn" either by issuing an alert to the user, or logging to the browser's console; I think the former is more likely to be spotted by, or reported back to, the site maintainers.

**Comment by RKrahl** [comment]
Striving for a foolproof `topcat.json` will be an ambitious endeavour.

I guess, if you just add `idsUpload*` back to `topcat.json.example`, set `enableUpload` to false as default, and document that `idsUploadDatafileFormat` and `idsUploadDatasetType` must be adapted to valid values in the ICAT if enabling upload, that would already be ok.
