### ISSUE TITLE
Update getSize cache

### ISSUE THREAD

**Issue by gc-code** [icatproject/topcat#394]
When an investigation is first seen in Topcat its size gets retrieved from the IDS and cached in the Topcat database. This cached size value is then never updated to reflect new files that are entered in the investigation.

This has caused problems at ISIS because a user has seen that their investigation has a size of 0 and assumed that it is empty. Topcat was just retrieving the 0 that had been cached for the getSize call, ignoring the fact that all the data had subsequently been ingested.

A quick fix would be to not cache 0 getSize values. These calls take very little time anyway.

**Comment by brianritchie1312** [comment]
I've created a branch, https://github.com/icatproject/topcat/tree/issue%23394-getSize-cache-consistency that adds finer-grained cache management for investigations, to both the Java (server) and Javascript (browser). Both can now be configured to set an age limit on Investigation size entries. The server cache can also be instructed never to cache zero sizes for Investigations (though as this is not possible in the browser it is not worth using without also setting an age limit in the browser).

There are new configuration properties in both topcat.properties and topcat.json; they are optional, so existing configurations will continue to work (with the original behaviour).

In order to add ageing on the server side, the Cache table requires an extra column, so there is a schema change to be applied. The simplest change is to drop the CACHE table!

It will be difficult to determine whether this is actually useful, as it needs to be tried on realistic volumes of data and user sessions.  I have tried to make sure that it is easy to reconfigure, including to the original behaviour.

During my local tests, I observed some disturbing behaviour: adding some debug log statements and watching the console suggests that there are multiple aysnchronous threads that are using the cache, and I am fairly sure that the same key is being stored multiple times.  The DB contains only one entry per key, but I am seeing multiple stores at roughly the same time, rather than a store followed by several retrievals. (This must also mean that there are multiple getSize requests back to the server, for the same entity.)  I suspect this has always been happening, but adding age limits (and thus forcing more frequent stores) may make this worse.  I don't know what could be done about this - assuming that it is worth trying.

**Comment by gc-code** [comment]
Thanks for looking into this. I'm not so worried about the ability to set a time limit on the validity of the cache. Once the initial burst of files are added to an investigation, it is unlikely that it will ever get a file added or removed again. Not caching zero sizes seems like it would solve my problem.

**Comment by brianritchie1312** [comment]
After further experiments, I believe that setting a short lifetime for cached investigation sizes in the browser is a bad idea. After the first browse to a page of investigations, if we return to the page after the caches have timed out, Topcat generates a large number of getSize requests back to the server. On a page of 5 investigations, I counted 40 "wasted" requests, where the cache had already been populated by the time the request completed. Disabling time-limits reduced this number to zero. I have seen occasional wasted requests since, but far fewer.

Given that the browser cache(s) can be cleared simply by reloading the page, I'm not convinced it's worth setting a lifetime for getSize requests at all, but I will leave it as a configuration option.

There is also a refresh function that clears all the browser caches; at present this only appears to be used by the upload mechanism (presumably on the basis that the uploaded data could make at least some of the cached sizes and query results inaccurate).

Topcat does set a timeout for cached query results; it is hard-wired at 10 hours. I don't know why that particular duration was chosen.
