### ISSUE TITLE
Make study accessible from topcat.json

### ISSUE THREAD

**Issue by gc-code** [icatproject/topcat#403]
I would like the study to be classified as a variable in Topcat. This would allow the contents of a study to be displayed by adding a line to topcat.json.

**Comment by gc-code** [comment]
On line 948 could the relationship just be called 'study' and line 510 'studyInvestigation'. This would be in keeping with the rest of the file.

**Comment by brianritchie1312** [comment]
I was following the example of investigation.relationships.investigationUsers. The 'pivot' name is used in the generated queries, but should not need to appear in topcat.json.  In the columnDefs for browse.investigation in topcat_dev.json, I have:

```javascript
                            {
                                "title": "Study",
                                "field": "investigationStudy.name"
                            },
```

I could change the variableName in studyInvestigation.relationships.study from 'investigationStudy' to just 'study'. It's not how it seems to be done for other relationships (perhaps because 'entityUsers' may be required by multiple 'entity' names); but 'study' isn't used anywhere else.
