### ISSUE TITLE
Topcat redirect handling

### ISSUE THREAD

**Issue by gc-code** [icatproject/topcat#424]
There are a number of places in Topcat where the user is redirected and the intermediate page is stored in the browser history. This makes the back button useless because it simply points back to the redirect page. It would be good if the back button were kept working throughout a user's entire interaction with Topcat.

**Comment by brianritchie1312** [comment]
There is a top-level $stateChangeError handler in Topcat: whenever a state change error occurs, if an authentication flag is false then Topcat sets the $state to 'login'. In commit 0362e87 (referenced above) I changed the handler so that it replaces the redirection in the doi-redirect case. However, I observe that the same issue happens whenever Topcat redirects to the login page (the redirection is left in the browser history so the Back button no longer works): just visiting the top-level Topcat URL when not authenticated will trigger this. So I am minded to change the handler so that it **always** replaces the redirection; but I'm concerned that there may be cases where this is not the right thing to do.
