### ISSUE TITLE
Restrict usage of access/download methods

### ISSUE THREAD

**Issue by kevinphippsstfc** [icatproject/topcat#428]
In the near future, we will be adding new download methods to the Diamond TopCAT for restoring data to SCARF (the SCD HPC cluster) and restoring data to the Diamond cluster. At least for restoring data to Diamond, this is likely to need to be only available to a restricted group of users so that it does not appear on the list of access methods for other users.

**Comment by brianritchie1312** [comment]
It may be fairly simple to add an optional "adminOnly" flag to download types so that they would only be visible to Topcat admin users. Anything more involved (e.g. restricting by some property of ICAT users / permissions, or adding an allowed list of users per download type in Topcat itself) would require a serious redesign, which is probably not worth doing.

**Comment by brianritchie1312** [comment]
Discussion with Diamond suggests that restriction of particular download types to particular groups of users is not required at present; so marking this as wontfix and closing.

**Comment by brianritchie1312** [comment]
See #337 - DLS agree that all that is required is to add a new download type to the configuration.
