### ISSUE TITLE
Search for Data across multiple ICAT servers

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#78]
## User Storey

As a user, I want to perform one single search across multiple servers for data.

## Acceptance Criteria
  - Search are performed only across ICAT servers that the user is currently logged into
  - Search results must appear as soon as they are streamed back ([streaming json](http://oboejs.com/)) from the server. Not wait until all results are returned from a server before showing.
  - If more than one facility, user must be able to select which facilities the search will be performed on
  - User must be able to add/edit/remove search parameters to a search
  - User must be able to add/edit/remove sample parameters to a search
  - User must be able to select what entity type (investigation, dataset, datafile) to return
  - The search must be bookmarkable

[Search Documentation](https://docs.google.com/document/d/1fJCexpcebyPFX_K5hXn9ZDqi0SdH8t2O81SrW1X5j6k/edit?usp=sharing)
[Mockup link](https://stfc.mybalsamiq.com/projects/topcatv2-stfc/Search%2001%20-%20Search)

**Comment by jodysalt** [comment]
I've had some other thoughts about the search feature. I think searching for everything by default is a good idea. However, each entity type can have a different set of columns in the results, so coming up with a meaningful generic set columns to view the results under could be tricky.

However, I have come up with an alternative solution.

How about we scrap the entity type drop down list, and instead have entity type tabs above the results; so after performing a search you can toggle between each entity type. Having these tabs would now be possible because the search feature is going to be under a separate tab to the browse feature.

What do you think?

**Comment by jodysalt** [comment]
Another solution could be that we don't use the UI grid component, and instead present google like search results i.e. a list rather than a table.

However, in terms of ranking it could also cause problems e.g. how do we decide that an Investigation that matches the keyword 'copper' is relevant than a Datafile that also matches the keyword 'copper'.  I guess it all depends on how the ranking algorithm actually works e.g. Investigation ranking scores might always be a lot larger that Datafiranking scores.

**Comment by fisherab** [comment]
It doesn't get round the problem that the set of fields that can be
specified is dependent upon what you are looking for.
