### ISSUE TITLE
Ability to browse results

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#84]
## User Storey

As a user, when results are returned from a search, I want to drill up and down the entity as though I am browsing its data tree struture

## Acceptance Criteria

[Mockup link - Dataset](https://stfc.mybalsamiq.com/projects/topcatv2-stfc/14a%20-%20Main%20page%20-%20Search%20-%20Result%20-%20Dataset)
[Mockup link - Datafile](https://stfc.mybalsamiq.com/projects/topcatv2-stfc/14b%20-%20Main%20page%20-%20Search%20-%20Result%20-%20Datafile)

**Comment by jodysalt** [comment]
This is not going to work in a way that will make sense to the user, because the parent entity may not necessarily match the child entities search criteria and vice versa.

For example say a Datafile matches the query "red" and the parent Dataset entity doesn't, imagine the following scenario. The user has found the Datafile, and then clicks on the link to the parent Dataset and then clicks the link to the parent Investigation, now the Dataset that we have just come from will have disappeared from search results as it doesn't match the query "red" - so we can't "drill up and down". Also date and parameter filters have different meanings depebding on the entity.

This style of navigation would work if we could search for all Datasets/Investigations that has a file that matches the query "red". 

As an alternative would simply linking the page in browse tree suffice? This is really simple for the end user - as it works like you'd expect any other search engine to work. How do see the user using this system? What problem(s) is this search feature trying to solve?

**Comment by jodysalt** [comment]
This ticket is basically an extension of #78 - and probably should have merged into it.
